# Generated by Django 5.2.1 on 2025-05-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_enrollement_quiz_quiz_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
    ]
