# Generated by Django 5.2.1 on 2025-05-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_video_alter_quiz_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_video',
            old_name='videoname',
            new_name='video_name',
        ),
        migrations.RemoveField(
            model_name='quiz_result',
            name='student',
        ),
    ]
