# Generated by Django 5.2.1 on 2025-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_quiz_result_quiz_delete_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='course_video',
        ),
    ]
