# Generated by Django 5.2.1 on 2025-05-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_video_course_course_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.course'),
            preserve_default=False,
        ),
    ]
