# Generated by Django 5.2.1 on 2025-05-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chapter_course_video_quiz_quiz_result_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_enrollement',
            name='Common_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.common_user'),
            preserve_default=False,
        ),
    ]
