# Generated by Django 5.2.1 on 2025-05-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_enrollement_common_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_enrollement',
            name='Common_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.common_user'),
        ),
        migrations.AlterField(
            model_name='course_enrollement',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
