# Generated by Django 5.2.1 on 2025-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_course_duration_alter_course_enrollement_common_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_user',
            name='qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common_user',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
