# Generated by Django 5.2.1 on 2025-05-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_common_user_qualification_common_user_university_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_enrollement',
            old_name='Common_user',
            new_name='common_user',
        ),
        migrations.AlterField(
            model_name='course_enrollement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='api.course'),
        ),
    ]
