# Generated by Django 5.2.1 on 2025-05-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_common_user_course_enrollement_common_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_enrollement',
            name='common_user',
        ),
        migrations.RemoveField(
            model_name='course_enrollement',
            name='date_enrolled',
        ),
        migrations.AlterField(
            model_name='course_enrollement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='course_enrollement',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_enrollement',
            name='Common_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.common_user'),
            preserve_default=False,
        ),
    ]
