# Generated by Django 5.2.1 on 2025-05-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_course_enrollement_common_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_enrollement',
        ),
    ]
